from __future__ import annotations

import os
import re


def comment_for_path(path: str, text: str) -> str:
    ext = os.path.splitext(path)[1].lower()
    if ext in {".ts", ".tsx", ".js", ".jsx", ".java", ".c", ".cpp", ".go", ".rs"}:
        return f"// {text}\n"
    if ext in {".py", ".sh", ".rb", ".yml", ".yaml"}:
        return f"# {text}\n"
    return f"{text}\n"


def component_name_from_file(file_name: str) -> str:
    stem = os.path.splitext(os.path.basename(file_name))[0]
    cleaned = re.sub(r"[^A-Za-z0-9_]", "", stem)
    if not cleaned:
        return "GeneratedComponent"
    return cleaned[0].upper() + cleaned[1:]


def generate_initial_content(*, safe_target: str, file_name: str, details: str, active_root: str) -> str:
    _ = active_root
    ext = os.path.splitext(safe_target)[1].lower()
    if ext in {".tsx", ".jsx"}:
        component_name = component_name_from_file(file_name)
        return (
            f"export default function {component_name}() {{\n"
            f"  return <div>{details or 'Generated component'}</div>;\n"
            "}\n"
        )
    if ext in {".ts", ".js"}:
        return "export {};\n"
    if ext == ".py":
        return "def main() -> None:\n    pass\n\n\nif __name__ == '__main__':\n    main()\n"
    if ext == ".md":
        return f"# {file_name}\n\n{details or 'Generated by dev graph.'}\n"
    return (details or "Generated by dev graph.") + "\n"

